name: Build

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Clone depot_tools
        run: |
          echo $PATH
          which python3
          which python
          which python2
          python3 --version
          python2 --version
          python --version
          export PATH="/usr/local/opt/python/libexec/bin:$PATH"
          echo $PATH
          python3 --version
          python2 --version
          python --version
          which python3
          which python2
          which python
