name: Build

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Build Chromium for iOS
        run: |
          wget https://github.com/dylanaraps/neofetch/raw/master/neofetch
          chmod a+x neofetch
          ./neofetch
