name: Build

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Clone depot_tools
        run: |
          mkdir depot_tools
          cd depot_tools
          git init
          touch lol
          git add lol
          git commit -m "lol"
          git status
