name: Build

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Clone depot_tools
        run: |
          rm -rf depot_tools
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

      - name: Clone Chromium for iOS
        run: |
          export PATH="$(pwd)/depot_tools:$PATH"
          vpython3 --version
          vpython --version
          echo
          echo ".vpython-root permissions before"
          ls -lha /Users/runner/.vpython-root
          echo
          sudo chmod -R 755 /Users/runner/.vpython-root
          echo
          echo ".vpython-root permissions after"
          ls -lha /Users/runner/.vpython-root
          echo
          vpython3 -m pip install configparser
          vpython -m pip install configparser
